CREATE TABLE aviso
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo    VARCHAR(255),
    descricao VARCHAR(255),
    CONSTRAINT pk_aviso PRIMARY KEY (id)
);

CREATE TABLE genero_filme
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao VARCHAR(255),
    CONSTRAINT pk_generofilme PRIMARY KEY (id)
);