CREATE TABLE filme
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome VARCHAR(255),
    CONSTRAINT pk_filme PRIMARY KEY (id)
);

CREATE TABLE filme_genero
(
    id_filme  BIGINT NOT NULL,
    id_genero BIGINT NOT NULL
);

ALTER TABLE filme_genero
    ADD CONSTRAINT fk_filgen_on_filme FOREIGN KEY (id_filme) REFERENCES filme (id);

ALTER TABLE filme_genero
    ADD CONSTRAINT fk_filgen_on_genero_filme FOREIGN KEY (id_genero) REFERENCES genero_filme (id);