CREATE TABLE cinema
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_hora            TIMESTAMP WITHOUT TIME ZONE,
    filme_selecionado_id BIGINT,
    CONSTRAINT pk_cinema PRIMARY KEY (id)
);

CREATE TABLE filme_sorteio
(
    id_cinema BIGINT NOT NULL,
    id_filme  BIGINT NOT NULL
);

ALTER TABLE cinema
    ADD CONSTRAINT FK_CINEMA_ON_FILMESELECIONADO FOREIGN KEY (filme_selecionado_id) REFERENCES filme (id);

ALTER TABLE filme_sorteio
    ADD CONSTRAINT fk_filsor_on_cinema FOREIGN KEY (id_cinema) REFERENCES cinema (id);

ALTER TABLE filme_sorteio
    ADD CONSTRAINT fk_filsor_on_filme FOREIGN KEY (id_filme) REFERENCES filme (id);