CREATE TABLE meme
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo       VARCHAR(255),
    descricao    VARCHAR(255),
    tipo_midia   VARCHAR(255),
    data_criacao TIMESTAMP WITHOUT TIME ZONE,
    criador_id   BIGINT,
    CONSTRAINT pk_meme PRIMARY KEY (id)
);

ALTER TABLE meme
    ADD CONSTRAINT FK_MEME_ON_CRIADOR FOREIGN KEY (criador_id) REFERENCES usuario (id);