CREATE TABLE data_comemorativa
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo       VARCHAR(255),
    descricao    VARCHAR(255),
    data_criacao TIMESTAMP WITHOUT TIME ZONE,
    data         date,
    criador_id   BIGINT,
    CONSTRAINT pk_datacomemorativa PRIMARY KEY (id)
);

ALTER TABLE data_comemorativa
    ADD CONSTRAINT FK_DATACOMEMORATIVA_ON_CRIADOR FOREIGN KEY (criador_id) REFERENCES usuario (id);